app/urls.py
from django.urls import path
from . import views



urlpatterns = [

    path('',views.index, name='home'),
    path('dashbord/', views.dash, name = 'dash'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.loginn, name='login'),
    path('logout/', views.logoutt, name='logout'),
    path('inscription/', views.signup, name='register'),
    path('add_event/', views.addevent, name='add_event'),
    path('new_ticket/<int:event_id>/', views.new_ticket, name='new_ticket'),
    path('success/', views.success, name='success'),
    path('Ticket_detail/<int:ticket_id>/', views.ticket_detail, name='ticket'),
    path('success/<int:ticket_id>/', views.success, name='success'),

]

tictac/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',views.index, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('app.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import ModelForm , TextInput
from django.urls import reverse


class AllUser(AbstractUser):
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='groups_related',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        verbose_name='groups',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='user_permissions_related',
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions',
    )
    username = None
    #is_verified = models.BooleanField(default=False)
    profil = models.FileField("Image de Profil",upload_to='Profil/')
    date_inscription = models.DateTimeField(auto_now=True)
    name = models.CharField("Entrer votre nom et prenom", max_length=80)
    email = models.EmailField( max_length=254, unique=True)
    phone = models.CharField('Telephone', max_length=50)
    status = models.CharField(max_length=50, default = '1')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "AllUser"
        verbose_name_plural = "AllUsers"

    def __str__(self):
        return self.name


    
class Event(models.Model):
    banniere = models.FileField("Affiche de l'evenement",upload_to='bannieres/')
    name = models.CharField("Nom de l'evenement", max_length=200)
    date_debut = models.DateTimeField('date de debut')
    user = models.ForeignKey(AllUser, on_delete=models.CASCADE)
    location = models.CharField('Lieu de l\'evenement', max_length=100)
    place_number = models.IntegerField('Nombre de place ', default = 0)
    description = models.TextField('description')
    is_actived = models.BooleanField(default=True)
    is_free = models.BooleanField(default= False)
    is_normal = models.IntegerField('Prix normal du ticket', default = 0)
    is_vip = models.IntegerField('prix du ticket VIP', default = 0)
    is_premium = models.IntegerField('prix du ticket Premium', default = 0)
    class Meta:
        verbose_name = ("Event")
        verbose_name_plural = ("Events")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Event_detail", kwargs={"pk": self.pk})



from django.core.validators import MinValueValidator
class Ticket(models.Model):
    name = models.CharField("Nom du ticket", max_length=50)
    price = models.IntegerField('Prix du ticket')
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    rang = models.CharField('phone', max_length=19)
    quantite = models.IntegerField('Combien de ticket voulez vous ?', default = 1, validators=[MinValueValidator(0)])
    class Meta:
        verbose_name = ("Ticket")
        verbose_name_plural = ("Tickets")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Ticket_detail", kwargs={"pk": self.pk})

app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm , TextInput
from django import forms
from .models import *


from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import AllUser

class AllUserCreationForm(UserCreationForm):
    class Meta:
        model = AllUser
        fields = ('profil','name', 'email', 'phone', 'status', 'password1', 'password2')  # Ajout des champs de mot de passe

    # Définition des champs du formulaire avec leurs attributs
    profil = forms.FileField(
        label='',
        widget=forms.FileInput(attrs={'class': 'profile-img-file-input', 'accept': 'image/*', 'required': True, 'data-max-file-size': '3MB','style':'display:none'})
    )
    name = forms.CharField(
        label='Nom et Prénom', 
        max_length=80,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Entrer votre nom et prénom'}),
    )
    email = forms.EmailField(
        label='Email', 
        max_length=254,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Entrez votre email'}),
    )
    phone = forms.CharField(
        label='Téléphone', 
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Entrez votre numéro de téléphone'}),
    )
    status = forms.CharField(
    label='Status',
    max_length=50,
    widget=forms.HiddenInput(attrs={'value': '1'}),  # Utilisation du widget HiddenInput pour cacher le champ
    initial='1',  # Valeur initiale du champ (non affichée)
)

    password1 = forms.CharField(
        label='Mot de passe',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Entrez votre mot de passe'}),
    )
    password2 = forms.CharField(
        label='Confirmation du mot de passe',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirmez votre mot de passe'}),
    )

    # Fonction de validation des mots de passe
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Les mots de passe ne correspondent pas.")
        return password2

    # Sauvegarde des données dans le modèle AllUser
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField(max_length=63, label='Nom d’utilisateur')
    password = forms.CharField(max_length=63, widget=forms.PasswordInput, label='Mot de passe')


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('place_number', 'banniere', 'date_debut', 'name', 'location', 'user', 'description', 'is_free', 'is_normal', 'is_vip', 'is_premium')
        widgets = {
            'place_number': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Numéro de place'}),
            
            'date_debut': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom de l\'événement'}),
            'location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Lieu'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description de l\'événement','rows':"3"}),
            'is_free': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'is_normal': forms.NumberInput(attrs={'class': 'form-control',}),
            'is_vip': forms.NumberInput(attrs={'class': 'form-control'}),
            'is_premium': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  
        
        super(EventForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['user'].initial = user  # Affecter l'utilisateur connecté au champ 'user' du formulaire
            self.fields['user'].widget = forms.HiddenInput()

from django.forms import ModelForm, TextInput, NumberInput

class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ('name', 'event', 'price', 'quantite', 'rang')
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom du ticket'}),
            'event': TextInput(attrs={'class': 'form-control', 'placeholder': 'Événement'}),
            'price': NumberInput(attrs={'class': 'form-control', 'placeholder': 'Prix'}),
            'quantite': NumberInput(attrs={'class': 'form-control', 'placeholder': 'Quantité'}),
            'rang': TextInput(attrs={'class': 'form-control', 'placeholder': 'le numero qui fera le payement'}),
        }

    
class QuantForm(forms.Form):
    quant = forms.CharField(max_length=63, label='')

app/templates/addevent.html
{% extends "layouts/base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'dash/libs/filepond/filepond.min.css' %}" type="text/css"  />
    <link rel="stylesheet" href="{% static 'dash/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.css' %}">
    <style>
        .contentDiv {
            transition: opacity 0.5s ease; /* Transition de fondu */
        }
        .hidden {
            opacity: 0; /* Définir l'opacité à 0 lorsque caché */
            pointer-events: none; /* Désactiver les événements sur les éléments cachés */
        }
  .upload-container {
    border: 2px dashed #ccc;
    border-radius: 5px;
    width: 300px;
    margin: 50px auto;
    padding: 20px;
    text-align: center;
  }
  .upload-container:hover {
    border-color: #333;
  }
  .upload-container input[type="file"] {
    width: 0.1px;
    height: 0.1px;
    opacity: 0;
    overflow: hidden;
    position: absolute;
    z-index: -1;
  }
  .upload-container label {
    font-size: 16px;
    font-weight: bold;
    color: #333;
    background-color: #fff;
    display: inline-block;
    cursor: pointer;
    padding: 10px 20px;
    margin: 10px;
  }
  .upload-container label:hover {
    background-color: #f7f7f7;
  }

  .image-preview {
    border: 2px solid blue;
    padding: 5px;
    margin-top: 10px;
  }
</style>
{% endblock link %}


{% block main %}
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="container-fluid">

                    <!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                                <h4 class="mb-sm-0">Add Event</h4>

                                <div class="page-title-right">
                                    <ol class="breadcrumb m-0">
                                        <li class="breadcrumb-item"><a href="javascript: void(0);">TIC</a></li>
                                        <li class="breadcrumb-item active">TAC</li>
                                    </ol>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!-- end page title -->
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5 class="card-title mb-0">Creer un nouvel Evenement</h5>
                                </div>
                                <div class="card-body">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="row g-3">                     
                                                <h5 class="fw-semibold mb-3"></h5>
                                                <div class="upload-container">
                                                    <input class="" type="file" name="banniere" accept="image/*" required="" id="id_banniere" data-max-file-size="3MB">
                                                    <label for="id_banniere" id="labelBanniere">
                                                       Ajouter l'affiche de l'événement
                                                    </label><div id="imagePreview" class="mt-3 w-100"></div>
                                                </div>
                                                
                                            <div class="col-lg-12">
                                                <label for="productName" class="form-label">Nom de L'evenement</label>
                                                {{form.name}}
                                            </div><!--end col-->
                                            <div class="col-lg-12">
                                                <label for="discription" class="form-label">Desciption</label>
                                                    {{form.description}}
                                            </div><!--end col-->
                                            <div class="col-lg-4">
                                                <label for="externalLink" class="form-label">Lieu</label>
                                                {{form.location}}
                                            </div>
                                            <div class="col-lg-4">
                                                <label for="externalLink" class="form-label">Date et Heure de l'evenement</label>
                                                {{form.date_debut}}
                                            </div>
                                            <div class="col-lg-4">
                                                <label for="externalLink" class="form-label">Nombre de place</label>
                                                {{form.place_number}}
                                            </div><!--end col-->
                                            <div class="col-lg-12">
                                                <div>
                                                    <div class="form-check form-check-inline">
                                                        {{form.is_free}}
                                                        <label class="form-check-label" for="inlineCheckbox2">L'evenement est gratuit</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 contentDiv">
                                                <label for="itemPrice" class="form-label">Ticket Classic Prix</label>
                                                {{form.is_normal}}
                                            </div><!--end col-->
                                            <div  class="col-lg-4 contentDiv">
                                                <label for="size" class="form-label">Ticket ViP Prix</label>
                                                {{form.is_vip}}
                                            </div><!--end col-->
                                            <div class="col-lg-4 contentDiv">
                                                <label for="properties" class="form-label">Ticket Premium Prix</label>
                                                {{form.is_premium}}
                                            </div>
                                            <!--end col-->
                                            {{form.user}}
                                            <!--end col-->
                                            <div class="col-lg-12">
                                                <div class="text-end">
                                                    <button type="submit" class="btn btn-primary">Creer l'Event</button>
                                                </div>
                                            </div>
                                        </><!--end row-->
                                    </form>
                                </div>
                            </div>
                        </div><!--end col-->
                    </div><!--end row-->

                </div>
                <!-- container-fluid -->
            </div>
            <!-- End Page-content -->
        </div>
        
    <!--nft create init js-->


{% endblock main %}


{% block script %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var inputBanniere = document.getElementById('id_banniere');
        var imagePreview = document.getElementById('imagePreview');
        
        if (inputBanniere && imagePreview) {
            inputBanniere.addEventListener('change', function(event) {
                var file = event.target.files[0];
                
                if (file) {
                    var reader = new FileReader();
                    
                    reader.onload = function(e) {
                        var image = new Image();
                        image.src = e.target.result;
                        image.classList.add('rounded', 'img-fluid'); // Ajoutez des classes Bootstrap ou personnalisées si nécessaire
                        
                        image.onload = function() {
                            imagePreview.innerHTML = '';
                            imagePreview.appendChild(image);
                        };
                    };
                    
                    reader.readAsDataURL(file);
                } else {
                    console.error('Aucun fichier sélectionné.');
                }
            });
        } else {
            console.error('Les éléments avec les ID id_banniere et imagePreview sont introuvables.');
        }
    });
    </script>
    
    

<script src="{% static 'dash/libs/filepond/filepond.min.js' %}"></script>
<script src="{% static 'dash/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.js' %}"></script>
<script src="{% static 'dash/libs/filepond-plugin-file-validate-size/filepond-plugin-file-validate-size.min.js' %}"></script>
<script src="{% static 'dash/libs/filepond-plugin-image-exif-orientation/filepond-plugin-image-exif-orientation.min.js' %}"></script>
<script src="{% static 'dash/libs/filepond-plugin-file-encode/filepond-plugin-file-encode.min.js' %}"></script>  

<script src="{% static 'dash/js/pages/apps-nft-create.init.js' %}"></script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        var hideCheckbox = document.getElementById("id_is_free");
        var contentDivs = document.querySelectorAll(".contentDiv");

        hideCheckbox.addEventListener("change", function() {
            if (this.checked) {
                contentDivs.forEach(function(div) {
                    div.classList.add("hidden");
                });
            } else {
                contentDivs.forEach(function(div) {
                    div.classList.remove("hidden");
                });
            }
        });
    });
</script>
{% endblock script %} 

app/templates/login.html
{% extends 'layouts/log.html' %}
{% load static %}
{% block main %}
<div class="row justify-content-center">
    <div class="col-md-8 col-lg-6 col-xl-5">
        <div class="card mt-4">
            <div class="card-body p-4">
                <div class="text-center mt-2">
                    {% for message in messages %}
                    <div style=" position: relative; bottom: 15px;"
                        class="alert btn-{{ message.tags }} alert-dismissible alert-label-icon rounded-label fade show" role="alert">
                        <i class="ri-notification-off-line label-icon"></i><strong>{{ message.tags }}</strong> - {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                    <h5 class="text-primary">Bienvenue à nouveau !</h5>
                    <p class="text-muted">Connectez-vous pour continuer vers TICTAC APP.</p>
                </div>
                <div class="p-2 mt-4">
                    <form class="needs-validation" novalidate method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="username" class="form-label">Email</label>
                            <input name="username" type="email" class="form-control" id="username" placeholder="Entrez votre adresse email" required>
                            <div class="invalid-feedback">
                                Veuillez entrer une adresse email valide.
                            </div>
                        </div>

                        <div class="mb-3">
                            <div class="float-end">
                                <a href="#" class="text-muted">Mot de passe oublié ?</a>
                            </div>
                            <label class="form-label" for="password-input">Mot de passe</label>
                            <div class="position-relative auth-pass-inputgroup mb-3">
                                <input name="password"  type="password" class="form-control pe-5 password-input" placeholder="Entrez votre mot de passe" id="password-input" required>
                                <div class="invalid-feedback">
                                    Veuillez entrer un mot de passe.
                                </div>
                                <button class="btn btn-link position-absolute end-0 top-0 text-decoration-none text-muted password-addon" type="button" id="password-addon"><i class="ri-eye-fill align-middle"></i></button>
                            </div>
                        </div>

                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="auth-remember-check">
                            <label class="form-check-label" for="auth-remember-check">Se souvenir de moi</label>
                        </div>

                        <div class="mt-4">
                            <button class="btn btn-success w-100" type="submit">Se connecter</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- fin du corps de la carte -->
        </div>
        <!-- fin de la carte -->

        <div class="mt-4 text-center">
            <p class="mb-0">Vous n'avez pas de compte ? <a href="{% url 'register' %}" class="fw-semibold text-primary text-decoration-underline">S'inscrire</a></p>
        </div>

    </div>
</div>


{% endblock main %}

app/templates/register.html
{% extends 'layouts/log.html' %}
{% load static %}
{% block link %}
<style>
    img {
      max-width: 100%;
      height: auto;
    }
  </style>
{% endblock link %}

{% block main %}

<div class="row justify-content-center">
    <div class="col-md-8 col-lg-6 col-xl-5">
        <div class="card mt-4">

            <div class="card-body p-4">
                <div class="text-center mt-2">
                    <h5 class="text-primary">Créer un nouveau compte</h5>
                    <p class="text-muted">Obtenez votre compte TIC-TAC</p>
                </div>
                    <div class="text-center">
                        <div class="profile-user position-relative d-inline-block mx-auto  mb-4">
                            <div id="imagePreview"><img class="rounded-circle avatar-xl img-thumbnail user-profile-image" src="{% static 'img/pp.png' %}" alt=""></div>
                            <div class="avatar-xs p-0 rounded-circle profile-photo-edit">
                                <label for="id_profil" class="profile-photo-edit avatar-xs">
                                    <span class="avatar-title rounded-circle bg-light text-body">
                                        <i class="ri-camera-fill"></i>
                                    </span>
                                </label>
                            </div>
                        </div>
                        <h5 class="fs-16 mb-1">Photo Profil</h5>
                    </div>
                <div class="p-2 mt-4">              
                    <form class="needs-validation" method="post" enctype="multipart/form-data">
                     {% csrf_token %}
                     {{form}}                
                        <div class="mb-4">
                            <p class="mb-0 fs-12 text-muted fst-italic">En vous inscrivant, vous acceptez nos <a href="#" class="text-primary text-decoration-underline fst-normal fw-medium">conditions d'utilisation</a></p>
                        </div>
                    
                        <div id="password-contain" class="p-3 bg-light mb-2 rounded">
                            <h5 class="fs-13">Le mot de passe doit contenir :</h5>
                            <p id="pass-length" class="invalid fs-12 mb-2">Minimum <b>8 caractères</b></p>
                            <p id="pass-lower" class="invalid fs-12 mb-2">Au moins une lettre <b>minuscule</b> (a-z)</p>
                            <p id="pass-upper" class="invalid fs-12 mb-2">Au moins une lettre <b>majuscule</b> (A-Z)</p>
                            <p id="pass-number" class="invalid fs-12 mb-0">Au moins un <b>chiffre</b> (0-9)</p>
                        </div>
                        
                        <div class="mt-4">
                            <button class="btn btn-success w-100" type="submit">S'inscrire</button>
                        </div>
                    </form>
                    
                </div>
            </div>
            <!-- end card body -->
        </div>
        <!-- end card -->

        <div class="mt-4 text-center">
            <p class="mb-0">J'ai deja un compte <a href="{% url "login" %}" class="fw-semibold text-primary text-decoration-underline"> Se Conneter</a> </p>
        </div>

    </div>
</div>
<!-- end row -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var idProfilInput = document.getElementById('id_profil');
        var imagePreview = document.getElementById('imagePreview');
        
        if (idProfilInput && imagePreview) {
            idProfilInput.addEventListener('change', function(event) {
                var file = event.target.files[0];
                
                if (file) {
                    var reader = new FileReader();
                    
                    reader.onload = function(e) {
                        var image = new Image();
                        image.src = e.target.result;
                        image.classList.add('rounded-circle', 'avatar-xl', 'img-thumbnail', 'user-profile-image');
                        
                        image.onload = function() {
                            imagePreview.innerHTML = '';
                            imagePreview.appendChild(image);
                        };
                    };
                    
                    reader.readAsDataURL(file);
                } else {
                    console.error('Aucun fichier sélectionné.');
                }
            });
        } else {
            console.error('Les éléments avec les ID id_profil et imagePreview sont introuvables.');
        }
    });
    </script>
    

{% endblock main %}